import React,{useState, useEffect} from 'react'
import { Col,Card, Divider, Row,Input,List  } from 'antd';
function Test() {
    const [value, setValue] = useState(0)
    const [reload, setReolad] = useState(0)
    const [word, setWord]= useState("")
    const [worng, setWorng]= useState([])

    useEffect(() => {
        const randomValue = ALLDATA[Math.floor(Math.random() * ALLDATA.length)];

        setWord(randomValue)
    }, [reload])
    

    const onPress = (e)=>{
        console.log(e.target.value)
        if(word.en===e.target.value){
            setReolad(p=>p+1)
            setValue("")
        }else{
            const tmp = worng
            tmp.push(word)
            setWorng(worng)
            setReolad(p=>p+1)
            setValue("")
        }   

       

    }

  return (
    <Row >
    <Col className="gutter-row" span={16}>
    <Card title={word.ko} bordered={false} style={{ width: 600 }}>
                <Input placeholder="Basic usage" onPressEnter={onPress} value={value} onChange={(e)=>{setValue(e.target.value)}}/>
    </Card>

      
    </Col>
    <Col className="gutter-row" span={8}>
    <List
   
      dataSource={worng}
      renderItem={(item) => (
        <List.Item>
          {item.ko} {item.en}
        </List.Item>
      )}
    />
    </Col>

  </Row>
  )
}

export default Test


const ALLDATA=[
{en:"abscess",ko:"종기, 농양"},
{en:"bruxism",ko:"이갈기"},
{en:"plaque",ko:"플라그"},
{en:"dental calculus",ko:"치석"},
{en:"dental tartar",ko:"치석"},
{en:"dental caries",ko:"충치"},
{en:"halitosis",ko:"구취"},
{en:"occlusion",ko:"교합"},
{en:"flatus",ko:"고창"},
{en:"anorexia",ko:"식욕 부진증"},
{en:"bulimia",ko:"폭식증"},
{en:"ascites",ko:"복수"},
{en:"atresia",ko:"폐쇄"},
{en:"cachexia",ko:"악액질"},
{en:"balanitis",ko:"귀두염"},
{en:"anorchism",ko:"무고환증"},
{en:"palatoschisis",ko:"구개열"},
{en:"malocclusion",ko:"부정교합"},
{en:"deglutition",ko:"연하"},
{en:"flatulence",ko:"고창"},
{en:"peristalsis",ko:"연동운동"},
{en:"achalasia",ko:"무이완증, 이완 불능증"},
{en:"neuter",ko:"거세, 고환절제술"},
{en:"priapism",ko:"음경 지속발기증"},
{en:"prostatitis",ko:"전립선염"},
{en:"prostatomegaly",ko:"전립선 비대증"},
{en:"prostatectomy",ko:"전립선 절제술"},
{en:"aspermia",ko:"무정자증"},
{en:"oligospermia",ko:"정자감소증"},
{en:"spermolysis",ko:"정자용해"},
{en:"spermatogenesis",ko:"정자형성, 정자발생"},
{en:"vasectomy",ko:"정관수술"},
{en:"hysterectomy",ko:"자궁적출술"},
{en:"hysteroscopy",ko:"자궁경검사"},
{en:"amniocentesis",ko:"양수검사"},
{en:"cervicitis",ko:"자궁경관염"},
{en:"endocervical",ko:"자궁경내의"},
{en:"colposcopy",ko:"질확대경 검사"},
{en:"colporrhaphy",ko:"질봉합술"},
{en:"colic",ko:"산통"},
{en:"drench",ko:"강제로 약먹이기"},
{en:"emaciation",ko:"쇠약, 수척함"},
{en:"enema",ko:"관장"},
{en:"eructation",ko:"트림"},
{en:"gavage",ko:"위관 영양법"},
{en:"jaundice",ko:"황달"},
{en:"icterus",ko:"황달"},
{en:"anorexia nervosa",ko:"거식증"},
{en:"belch",ko:"트림"},
{en:"melena",ko:"혈변, 흑색변"},
{en:"nausea",ko:"메스꺼움"},
{en:"palpation",ko:"촉진"},
{en:"pica",ko:"이식증"},
{en:"depraved appetite",ko:"이식증"},
{en:"regurgitate",ko:"되새김하다, 토하다"},
{en:"sours",ko:"설사(병)"},
{en:"stoma",ko:"작은구멍"},
{en:"tenesmus",ko:"이급후중"},
{en:"agalactia",ko:"무유증"},
{en:"cryptorchism",ko:"잠복고환"},
{en:"orchitis",ko:"고환염"},
{en:"orchectomy",ko:"고환절제술"},
{en:"orchiopexy",ko:"고환고정술"},
{en:"orchiectomy",ko:"거세, 고환절제술"},
{en:"orchidectomy",ko:"거세, 고환절제술"},
{en:"lactogenesis",ko:"젖생산"},
{en:"mammary",ko:"유방의"},
{en:"mammoplasty",ko:"유방성형술"},
{en:"mastitis",ko:"유방염, 유선염"},
{en:"mastectomy",ko:"유방절제술"},
{en:"metritis",ko:"자궁염"},
{en:"endometritis",ko:"자궁내막염"},
{en:"pyometritis",ko:"화농성자궁염"},
{en:"endometriosis",ko:"자궁내막증"},
{en:"neonatal",ko:"신생아의"},
{en:"oogenesis",ko:"난자형성, 난자발생"},
{en:"oocyte",ko:"난자"},
{en:"anovulation",ko:"무배란"},
{en:"oophorectomy",ko:"난소 적출술"},
{en:"ovarian",ko:"난소의"},
{en:"ovariohysterectomy",ko:"난소자궁 적출술"},
{en:"spay",ko:"난소자궁 적출술"},
{en:"antepartum",ko:"분만 전의"},
{en:"postpartum",ko:"분만 후의"},
{en:"pseudocyesis",ko:"상상임신, 가임신"},
{en:"oxytocia",ko:"급속분만"},
{en:"dystocia",ko:"난산, 이상분만"},
{en:"postmortem",ko:"검시, 사후조사"},
{en:"pelvimetry",ko:"산도측정"},
{en:"perineorrhaphy",ko:"회음 봉합술"},
{en:"multipara",ko:"다분만 산모"},
{en:"multiparous",ko:"다분만 산모"},
{en:"multigravida",ko:"다임신 산모"},
{en:"nullipara",ko:"미분만 산모"},
{en:"nulliparous",ko:"미분만 산모"},
{en:"nulligravida",ko:"미임신 산모"},
{en:"primipara",ko:"초산 산모"},
{en:"primiparous",ko:"초산 산모"},
{en:"primigravida",ko:"초임 산모"},
{en:"torsion",ko:"비틀림"},
{en:"volvulus",ko:"twisting on itself"},
{en:"trichobezoar",ko:"위모구"},
{en:"coitus",ko:"성교"},
{en:"conception",ko:"수정, 수태"},
{en:"fertilization",ko:"수정"},
{en:"eclampsia",ko:"유열(수유 중 칼슘이 낮아져서 오는 경련,"},
{en:"",ko:"코마)"},
{en:"milk fever",ko:"유열"},
{en:"abortion",ko:"절태술"},
{en:"angiogram",ko:"혈관 촬영도"},
{en:"angiopathy",ko:"맥관장애, 혈관병증"},
{en:"angiotomy",ko:"혈관 절개술"},
{en:"arteriectomy",ko:"동맥 절제술"},
{en:"arteriosclerosis",ko:"동맥 경화증"},
{en:"bradycardia",ko:"서맥"},
{en:"carditis",ko:"심장염"},
{en:"pericardiocentesis",ko:"심장막 천자술"},
{en:"pericardium",ko:"심막"},
{en:"cyanosis",ko:"청색증"},
{en:"anoxia",ko:"무산소증"},
{en:"phlebotomy",ko:"정맥 절개술"},
{en:"valvotomy",ko:"판막 절개술"},
{en:"valvoplasty",ko:"판막 성형술"},
{en:"diastole",ko:"확장기"},
{en:"sinus rhythm",ko:"normal heart rhythm"},
{en:"aneurysm",ko:"동맥류"},
{en:"auscultation",ko:"청진, 청음"},
{en:"embolism",ko:"색전증"},
{en:"hyperemia",ko:"충혈"},
{en:"ischemia",ko:"국소빈혈"},
{en:"bronchiectasis",ko:"기관지 확장증"},
{en:"bronchospasm",ko:"기관지 경련"},
{en:"bronchiolitis",ko:"세기관지염"},
{en:"capnograph",ko:"카프노그라프"},
{en:"",ko:"(호기중 탄소측정기)"},
{en:"pneumothorax",ko:"기흉"},
{en:"empyema",ko:"농흉"},
{en:"apnea",ko:"무호흡증"},
{en:"dyspnea",ko:"호흡곤란"},
{en:"pulmonectomy",ko:"폐절제술"},
{en:"bifurcation",ko:"분기"},
{en:"agonal respiration",ko:"사망직전 호흡"},
{en:"asphyxia",ko:"질식"},
{en:"copulation",ko:"성교"},
{en:"gestation",ko:"임신기간, 임신"},
{en:"colostrum",ko:"초유"},
{en:"fetotomy",ko:"절태술"},
{en:"embryotomy",ko:"절태술"},
{en:"leukorrhea",ko:"백대하"},
{en:"angioplasty",ko:"혈관 성형술"},
{en:"angiorrhaphy",ko:"혈관 봉합술"},
{en:"endarterectomy",ko:"동맥 내막 절제술"},
{en:"arteriotomy",ko:"동맥 절개술"},
{en:"arteriography",ko:"동맥 촬영술"},
{en:"cardiomegaly",ko:"심장비대증"},
{en:"endocarditis",ko:"심장내막염"},
{en:"tachycardia",ko:"빈맥"},
{en:"pericarditis",ko:"심막염"},
{en:"hypoxia",ko:"저산소증"},
{en:"phlebitis",ko:"정맥염"},
{en:"valvuloplasty",ko:"판막 성형술"},
{en:"vasculitis",ko:"맥관염"},
{en:"systole",ko:"수축기"},
{en:"arrhythmia",ko:"부정맥"},
{en:"asystole",ko:"무수축, 수축부전"},
{en:"cardiac tamponade",ko:"심장 눌림증, 심장 압전"},
{en:"flutter",ko:"이상박동, 심장조동"},
{en:"infarction",ko:"경색(증)"},
{en:"murmur",ko:"extra heart sound"},
{en:"bronchitis",ko:"기관지염"},
{en:"bronchoscopy",ko:"기관지경 검사"},
{en:"hypercapnia",ko:"과탄산증"},
{en:"hemothorax",ko:"혈흉"},
{en:"pyothorax",ko:"농흉"},
{en:"pleurodynia",ko:"흉막통증"},
{en:"bradypnea",ko:"완만호흡"},
{en:"tachypnea",ko:"급속호흡"},
{en:"lobectomy",ko:"폐엽절제술"},
{en:"atelectasis",ko:"폐확장 부전"},
{en:"antitussive",ko:"진해제, 기침약"},
{en:"aspiration",ko:"흡인"},
{en:"emphysema",ko:"폐기종"},
{en:"asthma",ko:"천식"},
{en:"epistaxis",ko:"nosebleed"},
{en:"hypopnea",ko:"호흡저하"},
{en:"palliative",ko:"일시적 처방, 대증처방"},
{en:"phlegm",ko:"가래, 담"},
{en:"purulent",ko:"화농성의"},
{en:"stridor",ko:"천명"},
{en:"sinusotomy",ko:"동절개술"},
{en:"tracheostomy",ko:"기관절개술"},
{en:"perfusion",ko:"관류"},
{en:"pericardial effusion",ko:"심막 내 삼출, 유출"},
{en:"sphygmomanometer",ko:"맥압계, 혈압계"},
{en:"stethoscope",ko:"청진기"},
{en:"stent",ko:"스텐트"},
{en:"anticoagulant",ko:"항응고제"},
{en:"coagulopathy",ko:"혈액응고 장애"},
{en:"hematopoiesis",ko:"혈액생성"},
{en:"hemostasis",ko:"지혈, 울혈"},
{en:"hemorrhage",ko:"출혈"},
{en:"hemophilia",ko:"혈우병"},
{en:"anemia",ko:"빈혈"},
{en:"coagulation",ko:"혈액응고"},
{en:"dyscrasia",ko:"혈액이상, 혈액병증"},
{en:"exsanguination",ko:"다량 출혈, 방혈"},
{en:"lipemia",ko:"지질혈증"},
{en:"interstitial space",ko:"간극층, 간질층"},
{en:"allergen",ko:"알러지 일으키는 물질"},
{en:"anaphylaxis",ko:"아나팔락시스"},
{en:"autoimmune disease",ko:"자가면역질환"},
{en:"edema",ko:"부종"},
{en:"febrile",ko:"열병, 열성의"},
{en:"hypersplenism",ko:"비기능 항진증"},
{en:"axillary",ko:"겨드랑이의"},
{en:"chemotherapy",ko:"화학요법"},
{en:"lymphadenitis",ko:"임파선염"},
{en:"lymphadenopathy",ko:"림프샘 장애"},
{en:"lymphangioma",ko:"임파관 종양"},
{en:"thymectomy",ko:"흉선 절제"},
{en:"tonsillitis",ko:"편도선염"},
{en:"hyperpnea",ko:"호흡항진"},
{en:"metastasis",ko:"전이"},
{en:"paroxysmal",ko:"발작성의"},
{en:"sputum",ko:"가래"},
{en:"rhonchi",ko:"나음, 라셀음, 수포음"},
{en:"sinusitis",ko:"부비강염, 축농증"},
{en:"spirometer",ko:"폐활량계"},
{en:"rouleaux",ko:"축산"},
{en:"anisocytosis",ko:"적혈구 대소구 부동증"},
{en:"poikilocytosis",ko:"변형적 적혈구 증가증"},
{en:"spherocytosis",ko:"구형(구상) 적혈구증"},
{en:"normochromic",ko:"정색성 적혈구"},
{en:"pancytopenia",ko:"범혈구감소증"},
{en:"erythroblast",ko:"적혈 모세포"},
{en:"erythrocytosis",ko:"적혈구 증가증"},
{en:"erythropenia",ko:"적혈구 감소증"},
{en:"erythropoiesis",ko:"적혈구 생성"},
{en:"homeostasis",ko:"항상성"},
{en:"hemoglobinopathy",ko:"이상 혈색소증"},
{en:"phagocyte",ko:"탐식세포"},
{en:"phagocytosis",ko:"탐식"},
{en:"myelogenous",ko:"골수성의, 골수에서 생긴"},
{en:"myeloid",ko:"골수의"},
{en:"myelopoiesis",ko:"골수 생성"},
{en:"myelodysplasia",ko:"골수 발달 이상"},
{en:"osteomyelodysplasia",ko:"골수 발달 이상"},
{en:"myelotomy",ko:"척수 절개술"},
{en:"myelomalacia",ko:"척수 연화증"},
{en:"myelogram",ko:"척수 조영술"},
{en:"aseptic",ko:"무균성의"},
{en:"antiseptic",ko:"소독된, 소독약"},
{en:"pyrexia",ko:"발열"},
{en:"antipyretic",ko:"해열제의"},
{en:"splenectomy",ko:"비장절제"},
{en:"splenomegaly",ko:"비장 비대증"},
{en:"staphylococci",ko:"포도상구균"},
{en:"streptococcus",ko:"연쇄상구균"},
{en:"toxic",ko:"유독성의"},
{en:"AB",ko:"Abortion"},
{en:"AI",ko:"Artificial Insemination"},
{en:"C-sect",ko:"Cesarean section"},
{en:"GU",ko:"Genitourinary"},
{en:"Gyn",ko:"Gynecology"},
{en:"OB",ko:"Obstetrics"},
{en:"PG",ko:"Pregnant"},
{en:"OHE, OVH",ko:"Spay"},
{en:"SF",ko:"Spayed female"},
{en:"NM (M/N)",ko:"Neutered male"},
{en:"CM",ko:"Castrated male"},
{en:"DCM",ko:"Dilated Cardiomyopathy 확장성 심근병증"},
{en:"HCM",ko:"Hypertrophic Cardiomyopathy 비대형 심근병증"},
{en:"DVT",ko:"Deep Vein Thrombosis"},
{en:"ECHO",ko:"Echocardiogram 초음파 심장 진단도"},
{en:"ECG, EKG",ko:"Electrocardiogram 심전도"},
{en:"HR",ko:"Heart Rate"},
{en:"MI",ko:"Myocardial Infarction 심근경색"},
{en:"MR",ko:"Mitral Regurgitation 승모판 역류"},
{en:"MVP",ko:"Mitral Valve Prolapse 승모판 일탈 증후군"},
{en:"PEA",ko:"Pulseless Electrical Activity 무맥성 전기활동"},
{en:"PDA",ko:"Patent Ductus Arteriosus 동맥관 개존증 (patent:열린)"},
{en:"SOB",ko:"Short Of Breath 호흡부족"},
{en:"V fib",ko:"Ventricular Fibrillation 심실세동"},
{en:"VSD",ko:"Ventricular Septal Defect 심실 중격 결손"},
{en:"ASD",ko:"Atrial Septal Defect 심방 중격 결손"},
{en:"ABG",ko:"Arterial Blood Gas 동맥혈 가스"},
{en:"BG",ko:"Blood Gas"},
{en:"BAL",ko:"Bronchoalveolar Lavage 기관지폐포 세척"},
{en:"CPA",ko:"Cardiopulmonary Arrest 심폐정지"},
{en:"CPR",ko:"Cardiopulmonary Resuscitation 심폐기능 소생술"},
{en:"PE",ko:"Pulmonary Embolism 폐색증"},
{en:"RR",ko:"Respiratory Rate 호흡 수"},
{en:"qn",ko:"Every night (quaque nocte)"},
{en:"qd",ko:"Every day (quaque die)"},
{en:"qh",ko:"Every hour (quaque hora)"},
{en:"BID",ko:"Twice daily: q12h (Bis In Die)"},
{en:"SID",ko:"Once daily: q24h (Semel In Die)"},
{en:"BIN",ko:"Twice a night (Bis In Nocte)"},
{en:"TID",ko:"Three times daily: q8h (Ter In Die)"},
{en:"QID",ko:"Four times daily: q6h (Quad In Die)"},
{en:"EOD",ko:"Every Other Day"},


]